import { listPets, Pet } from "autogenerated/index";
import { getButton } from "ui/index";

const run = () => {
  listPets().then((pets) => {
    const petNames = pets.map((pet: Pet) => pet.name);
    const button = getButton(petNames.join(", "));
    document.body.appendChild(button);
  });
};

run();
